test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>


google_dev:
  service: GCS
  project: rails-qna
  credentials: <%= Rails.root.join("config/secrets/qna.json") %>
  bucket: qna-pics-bucket

# local:
#   service: Disk
#   root: <%= Rails.root.join("storage") %>

# google:
#   service: GCS
#   project: rails-qna
#   credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
#   bucket: qna-pics-bucket
